<a href="https://colab.research.google.com/github/YonggunJung/gitp/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
from os.path import join

pj_path = '/content/drive/MyDrive/Colab Notebooks/github/colab/'
# 여기 위치로 열기 (파일 생성 장소)
%cd '{pj_path}'
%pwd

/content/drive/MyDrive/Colab Notebooks/github/colab


'/content/drive/MyDrive/Colab Notebooks/github/colab'

In [36]:
# 열기
with open(pj_path + 'HW.txt', 'r') as f:
  c = f.read()
print(c)

헬로우 워울드


In [37]:
import numpy as np


In [38]:
np.__version__

'1.23.5'

In [39]:
len(dir(np))

603

In [40]:
# 리스트 생성
mylist = [1, 2, 3, 4, 5]
type(mylist), mylist

(list, [1, 2, 3, 4, 5])

In [41]:
# 리스트 를 넘파이 배열로
arr = np.array(mylist)
type(arr), arr

(numpy.ndarray, array([1, 2, 3, 4, 5]))

In [42]:
#  콤마 사라짐
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [43]:
# 리스트 데이터형 혼합 가능
#  정수 실수 가능
mylist22 = [0, 1, 3.5, 100, -6.7]
mylist22

[0, 1, 3.5, 100, -6.7]

In [44]:
# 넘파이 배열 데이터형 혼합 불가 => 단일화
#  정수 실수 함께 있으면 실수로 통합
arr22 = np.array([0, 1, 3.5, 100, -6.7])
arr22

array([  0. ,   1. ,   3.5, 100. ,  -6.7])

In [45]:
# 문자열형 넘파이 배열
# 문자열, 정수, 실수, 불형 => 문자열로 통합
arr33 = np.array(['파이썬', '자바', 'HTML', 100, 2.24, True])
arr33

array(['파이썬', '자바', 'HTML', '100', '2.24', 'True'], dtype='<U32')

In [46]:
# 1차원 넘파이 배열
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(arr1.shape)
print(arr1.ndim)
print(arr1.size)
len(arr1)

[1 2 3 4 5]
(5,)
1
5


5

In [47]:
# 2차원 리스트
mylist2 = [[1, 2, 3], [100, 200], [1000]]
mylist2

[[1, 2, 3], [100, 200], [1000]]

In [48]:
# 2차원 넘파이 배열 구성요소 길이가 다른 경우
arr2 = np.array([[1, 2, 3], [100, 200], [1000]])
print(arr2)
print(arr2.shape)
print(arr2.ndim)
print(arr2.size)
len(arr2)

[list([1, 2, 3]) list([100, 200]) list([1000])]
(3,)
1
3


<ipython-input-48-6295cd020c2f>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr2 = np.array([[1, 2, 3], [100, 200], [1000]])


3

In [49]:
# 2차원 넘파이 배열 구성요소 길이가 같은경우
arr3 = np.array([[1, 2, 3], [100, 200,300], [1000, 2000, 3000]])
print(arr3)
print(arr3.shape)
print(arr3.ndim)
print(arr3.size)
len(arr3)

[[   1    2    3]
 [ 100  200  300]
 [1000 2000 3000]]
(3, 3)
2
9


3

In [50]:
# 리스트 인덱싱
mlist = [1, 2, 3, 4, 5]
mlist[0], mlist[-1]

(1, 5)

In [51]:
# 2차원 리스트 인덱싱
mlist2 = [[1, 2, 3], [100, 200], [1000]]
mlist2[0], mlist2[-1], mlist2[0][0], mlist2[-2][1]

([1, 2, 3], [1000], 1, 200)

In [52]:
# 넘파이 배열 인덱싱
arr1 = np.array([1, 2, 3, 4, 5])
arr1[0], arr1[-1]

(1, 5)

In [53]:
# 2차원 넘파이 배열 인덱싱 - 행인덱스, 열인덱스 가능
arr2 = np.array([[1, 2, 3], [100, 200,300], [1000, 2000, 3000]])
arr2[0], arr2[0][0], arr2[-1], arr2[-1][0]

(array([1, 2, 3]), 1, array([1000, 2000, 3000]), 1000)